minimum_pre_commit_version: "3.6.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --with ruff ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run --with ruff ruff format
        language: system
        types_or: [python, pyi]

      - id: bandit
        name: bandit
        entry: uv run --with bandit[toml] bandit
        args:
          - -c
          - pyproject.toml
          - --severity-level
          - medium
          - --confidence-level
          - medium
        language: system
        files: ^(packages|algorithms)/.*\.py$
        exclude: (^|/)(tests?/|test_.*\.py$)

      - id: detect-secrets
        name: detect-secrets
        entry: uv run --with detect-secrets detect-secrets-hook
        args:
          - --baseline
          - .secrets.baseline
          - --exclude-files
          - (^\.secrets\.baseline$|\.ipynb$)
          - -n
        language: system
