"""
PBS script generator for Miyabi demo.
"""

from __future__ import annotations
from pathlib import Path

from .resolver import ResolvedRun


PBS_TEMPLATE = """#!/bin/bash
# ==== Miyabi PBS job script generated by Prefect demo (MPI hello) ====
#PBS -q {queue}
#PBS -l select={nodes}:ncpus={ncpus_per_node}
#PBS -l walltime={walltime}
#PBS -N {job_name}
#PBS -W group_list=gz09
#PBS -j oe
{project_line}

set -euo pipefail
cd "${{PBS_O_WORKDIR:-$PWD}}"



# --- Environment setup (merged) ---
{module_init_block}
{module_load_block}
{spack_block}

# --- Threading ---
export OMP_NUM_THREADS={threads_per_rank}

{env_exports}

echo "[INFO] queue={queue} nodes={nodes} ranks_per_node={ranks_per_node} threads_per_rank={threads_per_rank}"
echo "[INFO] total_ranks={total_ranks}"
echo "[INFO] cmd: {cmdline}"

{launch_line}

echo "[INFO] done"
"""


def _quote(s: str) -> str:
    if not s:
        return "''"
    if any(c in s for c in " \t\n\"'\\$`"):
        return "'" + s.replace("'", "'\"'\"'") + "'"
    return s


def write_pbs_script(run: ResolvedRun, *, out_dir: Path, job_name: str) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    cmdline = " ".join(_quote(a) for a in run.argv)

    ncpus_per_node = run.ranks_per_node * run.threads_per_rank
    project_line = f"#PBS -P {run.project}" if run.project else ""

    module_init_block = "\n".join(run.module_init) if run.module_init else ""
    module_load_block = "\n".join([f"module load {m}" for m in run.modules]) if run.modules else ""

    if run.spack_setup or run.spack_load:
        lines = []
        if run.spack_setup:
            lines.append(f". {run.spack_setup}")
        for m in run.spack_load:
            lines.append(f"spack load {m}")
        spack_block = "\n".join(lines)
    else:
        spack_block = ""

    env_exports = "\n".join([f'export {k}="{v}"' for k, v in run.env.items()]) if run.env else ""

    if run.launcher == "single":
        launch_line = cmdline
    else:
        launch = "mpiexec.hydra"
        launch_line = f"{launch} -np {run.total_ranks} {cmdline}"

    script = PBS_TEMPLATE.format(
        queue=run.queue,
        nodes=run.nodes,
        ncpus_per_node=ncpus_per_node,
        walltime=run.walltime,
        job_name=job_name,
        project_line=project_line,
        module_init_block=module_init_block,
        module_load_block=module_load_block,
        spack_block=spack_block,
        threads_per_rank=run.threads_per_rank,
        env_exports=env_exports,
        ranks_per_node=run.ranks_per_node,
        total_ranks=run.total_ranks,
        cmdline=cmdline,
        launch_line=launch_line,
    )

    path = out_dir / f"{job_name}.pbs.sh"
    path.write_text(script, encoding="utf-8")
    path.chmod(0o755)
    return path
